const backendEnvironment = () => ({
  AUTH_COOKIE_SECURE: "true",
  AWS_ACCESS_KEY_ID: "test-access-key",
  AWS_REGION: "ap-southeast-1",
  AWS_S3_BUCKET_NAME: "kittachat-public-demo-nhibuaa",
  AWS_SECRET_ACCESS_KEY: "test-secret-key",
  CALL_DISTRIBUTED_TIMEOUT_ENABLED: "false",
  CALL_DISTRIBUTED_TIMEOUT_POLL_MS: "1000",
  CONVERSATION_DUAL_WRITE_ENABLED: "false",
  CONVERSATION_PANEL_ENABLED: "false",
  CONVERSATION_PANEL_RATE_LIMIT: "30",
  CONVERSATION_PANEL_RESOURCES_ENABLED: "false",
  CONVERSATION_SHADOW_COMPARE_ENABLED: "false",
  CONVERSATION_SIDEBAR_READ_MODEL_ENABLED: "false",
  CORS_ALLOWED_ORIGINS: "https://kittachat-public-demo.test",
  DEFAULT_AVATAR: "https://assets.example.test/avatar.png",
  JWT_SECRET: "test-jwt-secret",
  K6_CAPABILITY_CALLS: "true",
  K6_CAPABILITY_GOOGLE_LOGIN: "false",
  K6_CAPABILITY_ISSUE61_MEASUREMENT: "false",
  K6_CAPABILITY_RECOVERY: "false",
  K6_CAPABILITY_UPLOAD: "false",
  K6_SYNTHETIC_SIGNUP_ONLY: "true",
  K6_TARGET: "public-demo",
  METRICS_ENABLED: "false",
  MONGO_URI: "mongodb://database.invalid/shot-chat",
  NODE_ENV: "production",
  NODE_NAME: "backend",
  PORT: "3000",
  RABBITMQ_MAX_ATTEMPTS: "3",
  RABBITMQ_RETRY_DELAY_MS: "30000",
  RABBITMQ_URL: "amqps://broker.invalid/vhost",
  RABBITMQ_WORKER_MAX_RECONNECT_DELAY_MS: "30000",
  RABBITMQ_WORKER_RECONNECT_DELAY_MS: "1000",
  REDIS_RATE_LIMIT_CLUSTER_ROOT_NODES: "",
  REDIS_URL: "rediss://redis.invalid:6379",
  REFRESH_TOKEN_SECRET: "test-refresh-secret",
  URL_FRONTEND: "https://kittachat-public-demo.test",
});

const imageWorkerEnvironment = () => ({
  AWS_ACCESS_KEY_ID: "test-access-key",
  AWS_REGION: "ap-southeast-1",
  AWS_S3_BUCKET_NAME: "kittachat-public-demo-nhibuaa",
  AWS_SECRET_ACCESS_KEY: "test-secret-key",
  IMAGE_WORKER_CONCURRENCY: "2",
  MONGO_URI: "mongodb://database.invalid/shot-chat",
  NODE_ENV: "production",
  NODE_NAME: "image-worker",
  RABBITMQ_MAX_ATTEMPTS: "3",
  RABBITMQ_RETRY_DELAY_MS: "30000",
  RABBITMQ_URL: "amqps://broker.invalid/vhost",
  RABBITMQ_WORKER_MAX_RECONNECT_DELAY_MS: "30000",
  RABBITMQ_WORKER_RECONNECT_DELAY_MS: "1000",
  REDIS_URL: "rediss://redis.invalid:6379",
});

const auditWorkerEnvironment = () => ({
  AUDIT_WORKER_CONCURRENCY: "10",
  NODE_ENV: "production",
  NODE_NAME: "audit-worker",
  RABBITMQ_MAX_ATTEMPTS: "3",
  RABBITMQ_RETRY_DELAY_MS: "30000",
  RABBITMQ_URL: "amqps://broker.invalid/vhost",
  RABBITMQ_WORKER_MAX_RECONNECT_DELAY_MS: "30000",
  RABBITMQ_WORKER_RECONNECT_DELAY_MS: "1000",
});

const edgeRuntimeEnvironment = () => ({
  BACKEND_UPSTREAM: "backend.railway.internal:3000",
  K6_CAPABILITY_CALLS: "true",
  K6_CAPABILITY_GOOGLE_LOGIN: "false",
  K6_CAPABILITY_ISSUE61_MEASUREMENT: "false",
  K6_CAPABILITY_RECOVERY: "false",
  K6_CAPABILITY_UPLOAD: "false",
  K6_RUNTIME_CONFIG_FILE: "/etc/nginx/runtime-config.json",
  K6_TARGET: "public-demo",
});

const edgeBuildEnvironment = () => ({
  VITE_API_URL: "/",
  VITE_API_URL_AUTH: "/api/auth",
  VITE_API_URL_CALLS: "/api/calls",
  VITE_API_URL_FILES: "/api/files",
  VITE_API_URL_GROUPS: "/api/groups",
  VITE_API_URL_MESSAGES: "/api/messages",
  VITE_API_URL_USERS: "/api/users",
  VITE_TARGET: "public-demo",
});

const oneOffSeedEnvironment = () => ({
  ALLOW_REMOTE_DEMO_SEED: "true",
  DEMO_SEED_PASSWORD: "test-memory-password",
  MONGO_URI: "mongodb://database.invalid/shot-chat",
});

const identityRows = Object.freeze([
  ["V01", "Visitor@KittaChat.Test", true, "visitor@kittachat.test"],
  ["V02", "visitor@team.kittachat.test", true, "visitor@team.kittachat.test"],
  ["R01", undefined, false],
  ["R02", null, false],
  ["R03", 42, false],
  ["R04", " visitor@kittachat.test", false],
  ["R05", "visitor@kittachat.test ", false],
  ["R06", "visitor @kittachat.test", false],
  ["R07", "visitor\u0009@kittachat.test", false],
  ["R08", "visitor\u200B@kittachat.test", false],
  ["R09", "visitor@kittachat\u3002test", false],
  ["R10", "visitor@kittachat\uFF0Etest", false],
  ["R11", "visitorkittachat.test", false],
  ["R12", "visitor@@kittachat.test", false],
  ["R13", "@kittachat.test", false],
  ["R14", "visitor@test", false],
  ["R15", "visitor@.test", false],
  ["R16", "visitor@kittachat..test", false],
  ["R17", "visitor@-kittachat.test", false],
  ["R18", "visitor@kittachat-.test", false],
  ["R19", "visitor@kittachat.test.", false],
  ["R20", "visitor@example.com", false],
  ["R21", "visitor@kittachat.test.evil", false],
  ["R22", "visitor@kittachattest", false],
  ["R23", "visitor@test.evil", false],
  ["R24", "visitor@*.test", false],
  ["R25", "visitor:opaque@kittachat.test", false],
]);

const expectedPolicies = Object.freeze({
  "auth_entry.aggregate": ["sliding_window", 20, 900000, null, "network"],
  "auth_entry.login": ["sliding_window", 10, 900000, null, "network"],
  "auth_entry.register": ["sliding_window", 5, 3600000, null, "network"],
  "auth_entry.google": ["sliding_window", 10, 900000, null, "network"],
  auth_recovery_request: ["sliding_window", 5, 3600000, null, "network"],
  auth_recovery_complete: ["sliding_window", 10, 900000, null, "network"],
  "auth_refresh.stage_a": ["token_bucket", 60, 60000, 10, "network"],
  "auth_refresh.stage_b": ["token_bucket", 20, 60000, 5, "subject"],
  "file_resource.aggregate": ["token_bucket", 300, 3600000, 50, "user"],
  "file_resource.upload_control": ["token_bucket", 30, 3600000, 10, "user"],
  "file_resource.part_presign": ["token_bucket", 240, 3600000, 40, "user"],
  "file_resource.download_signing": ["token_bucket", 120, 3600000, 30, "user"],
  call_initiation: ["sliding_window", 10, 60000, null, "socket_user"],
  "read_expensive.aggregate": ["token_bucket", 240, 60000, 60, "user"],
  "read_expensive.call_history": ["token_bucket", 30, 60000, 10, "user"],
  "state_mutation.aggregate": ["token_bucket", 120, 60000, 30, "user"],
  "state_mutation.call_history": ["token_bucket", 120, 60000, 30, "user"],
});

const expectedOperationPolicies = Object.freeze({
  "POST /api/auth/login": ["auth_entry.aggregate", "auth_entry.login"],
  "POST /api/auth/register": ["auth_entry.aggregate", "auth_entry.register"],
  "POST /api/auth/google": ["auth_entry.aggregate", "auth_entry.google"],
  "POST /api/auth/forgot-password": ["auth_recovery_request"],
  "POST /api/auth/reset-password/:id": ["auth_recovery_complete"],
  "POST /api/auth/refresh stage A": ["auth_refresh.stage_a"],
  "refresh subject admission stage B": ["auth_refresh.stage_b"],
  "POST /api/files/init": ["file_resource.aggregate", "file_resource.upload_control"],
  "POST /api/files/get-presigned-url": ["file_resource.aggregate", "file_resource.part_presign"],
  "POST /api/files/complete": ["file_resource.aggregate", "file_resource.upload_control"],
  "POST /api/files/upload-single": ["file_resource.aggregate", "file_resource.upload_control"],
  "POST /api/files/:fileId/download-url": ["file_resource.aggregate", "file_resource.download_signing"],
  "GET /api/calls/history": ["read_expensive.aggregate", "read_expensive.call_history"],
  "GET /api/calls/missed": ["read_expensive.aggregate", "read_expensive.call_history"],
  "POST /api/calls/:id/read": ["state_mutation.aggregate", "state_mutation.call_history"],
  "POST /api/calls/read-all": ["state_mutation.aggregate", "state_mutation.call_history"],
  "Socket.IO initCall": ["call_initiation"],
  "Socket.IO callUser": ["call_initiation"],
  "Socket.IO answerCall": [],
  "Socket.IO endCall": [],
  "Socket.IO rejectCall": [],
  "Socket.IO toggleMedia": [],
});

module.exports = {
  auditWorkerEnvironment,
  backendEnvironment,
  edgeBuildEnvironment,
  edgeRuntimeEnvironment,
  expectedOperationPolicies,
  expectedPolicies,
  identityRows,
  imageWorkerEnvironment,
  oneOffSeedEnvironment,
};
