name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  server-tests:
    name: Server Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node environment
        uses: ./.github/actions/setup-node-env
        with:
          working-directory: server
          cache-dependency-path: server/package-lock.json

      - name: Run server tests
        run: npm test

  client-tests:
    name: Client Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node environment
        uses: ./.github/actions/setup-node-env
        with:
          working-directory: client
          cache-dependency-path: client/package-lock.json

      - name: Run client tests
        run: npm test
